
INSERT INTO book (id, title, genre, summary)
VALUES
(1, 'Clean Code: A Handbook of Agile Software Craftsmanship', 'Coding', 'Even bad code can function. But if code isn t clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code. But it doesn t have to be that way.'),
(2, 'UML Distilled: A Brief Guide to the Standard Object Modeling Language', 'Coding', 'More than 300,000 developers have benefited from past editions of UML Distilled . This third edition is the best resource for quick, no-nonsense insights into understanding and using UML 2.0 and prior versions of the UML.'),
(3, 'The Alchemist', 'Fiction', 'Paulo Coelho s enchanting novel has inspired a devoted following around the world. This story, dazzling in its powerful simplicity and soul-stirring wisdom, is about an Andalusian shepherd boy named Santiago who travels from his homeland in Spain to the near the Pyramids.'),
(4, '1984', 'Political-fiction', 'Among the seminal texts of the 20th century, Nineteen Eighty-Four is a rare work that grows more haunting as its futuristic purgatory becomes more real. Published in 1949, the book offers political satirist George Orwell''s nightmarish vision of a totalitarian, bureaucratic world and one poor stiff''s attempt to find individuality.'),
(5, 'The social atom', 'Social', 'Nice overview of the evolution of sociology into a "real" science, with solid examples across various topics. Felt like it was missing some kind of point or conclusion.'),
(6, 'A Confession', 'Biography', 'A Confession -- an essay by Leo Tolstoy on his religious thoughts -- shows the great author in process of looking for answers to profound questions that trouble all who take them on: "What will come of my life?" and "What is the meaning of life?" these are questions whose answers were an absolute requirement for Tolstoy.'),
(7, 'War and Peace', 'Historical-fiction', 'In Russia''s struggle with Napoleon, Tolstoy saw a tragedy that involved all mankind. Greater than a historical chronicle, War and Peace is an affirmation of life itself, `a complete picture'', as a contemporary reviewer put it, `of everything in which people find their happiness and greatness, their grief and humiliation''.'),
(8, 'الدكتور جيكل والسيد هايد', 'أدب', '«الدكتور جيكل والسيد هايد» هي رواية كتبها المؤلف الأسكتلندي الشهير روبرت لويس ستيفنسون نُشرت للمرة الأولى عام ١٨٨٦، وتدور أحداثها حول محامي يقطن لندن يُدعى السيد أترسون يقوم بالتقصي عن أحداث غريبة تقع لصديقه القديم دكتور هنري جيكل وإدوارد هايد الشرير.');

